// go:generate protoc --go_out=../../pkg/grpc --go_opt=paths=source_relative music.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: music.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Music struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MusicName string `protobuf:"bytes,2,opt,name=music_name,json=musicName,proto3" json:"music_name,omitempty"`
	Hiragana  string `protobuf:"bytes,3,opt,name=hiragana,proto3" json:"hiragana,omitempty"`
	Artist    string `protobuf:"bytes,4,opt,name=artist,proto3" json:"artist,omitempty"`
	Key       uint32 `protobuf:"varint,5,opt,name=key,proto3" json:"key,omitempty"`
	MaxKey    string `protobuf:"bytes,6,opt,name=max_key,json=maxKey,proto3" json:"max_key,omitempty"`
	MaxScore  string `protobuf:"bytes,7,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	UserId    string `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Modified  string `protobuf:"bytes,9,opt,name=modified,proto3" json:"modified,omitempty"`
	Created   string `protobuf:"bytes,10,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *Music) Reset() {
	*x = Music{}
	if protoimpl.UnsafeEnabled {
		mi := &file_music_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Music) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Music) ProtoMessage() {}

func (x *Music) ProtoReflect() protoreflect.Message {
	mi := &file_music_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Music.ProtoReflect.Descriptor instead.
func (*Music) Descriptor() ([]byte, []int) {
	return file_music_proto_rawDescGZIP(), []int{0}
}

func (x *Music) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Music) GetMusicName() string {
	if x != nil {
		return x.MusicName
	}
	return ""
}

func (x *Music) GetHiragana() string {
	if x != nil {
		return x.Hiragana
	}
	return ""
}

func (x *Music) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Music) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Music) GetMaxKey() string {
	if x != nil {
		return x.MaxKey
	}
	return ""
}

func (x *Music) GetMaxScore() string {
	if x != nil {
		return x.MaxScore
	}
	return ""
}

func (x *Music) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Music) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

func (x *Music) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

type GetMusicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMusicRequest) Reset() {
	*x = GetMusicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_music_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMusicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMusicRequest) ProtoMessage() {}

func (x *GetMusicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_music_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMusicRequest.ProtoReflect.Descriptor instead.
func (*GetMusicRequest) Descriptor() ([]byte, []int) {
	return file_music_proto_rawDescGZIP(), []int{1}
}

func (x *GetMusicRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMusicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Music *Music `protobuf:"bytes,1,opt,name=music,proto3" json:"music,omitempty"`
}

func (x *GetMusicResponse) Reset() {
	*x = GetMusicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_music_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMusicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMusicResponse) ProtoMessage() {}

func (x *GetMusicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_music_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMusicResponse.ProtoReflect.Descriptor instead.
func (*GetMusicResponse) Descriptor() ([]byte, []int) {
	return file_music_proto_rawDescGZIP(), []int{2}
}

func (x *GetMusicResponse) GetMusic() *Music {
	if x != nil {
		return x.Music
	}
	return nil
}

type GetAllMusicsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAllMusicsRequest) Reset() {
	*x = GetAllMusicsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_music_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllMusicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMusicsRequest) ProtoMessage() {}

func (x *GetAllMusicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_music_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMusicsRequest.ProtoReflect.Descriptor instead.
func (*GetAllMusicsRequest) Descriptor() ([]byte, []int) {
	return file_music_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllMusicsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllMusicsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Music *Music `protobuf:"bytes,1,opt,name=music,proto3" json:"music,omitempty"`
}

func (x *GetAllMusicsResponse) Reset() {
	*x = GetAllMusicsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_music_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllMusicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMusicsResponse) ProtoMessage() {}

func (x *GetAllMusicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_music_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMusicsResponse.ProtoReflect.Descriptor instead.
func (*GetAllMusicsResponse) Descriptor() ([]byte, []int) {
	return file_music_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllMusicsResponse) GetMusic() *Music {
	if x != nil {
		return x.Music
	}
	return nil
}

var File_music_proto protoreflect.FileDescriptor

var file_music_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d,
	0x75, 0x73, 0x69, 0x63, 0x22, 0x81, 0x02, 0x0a, 0x05, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x69, 0x72, 0x61, 0x67, 0x61, 0x6e, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x69, 0x72, 0x61, 0x67, 0x61, 0x6e, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x61, 0x78, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x61, 0x78, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d,
	0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x05, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x05, 0x6d, 0x75,
	0x73, 0x69, 0x63, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x75, 0x73,
	0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52,
	0x05, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x32, 0x98, 0x01, 0x0a, 0x0c, 0x4d, 0x75, 0x73, 0x69, 0x63,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x75,
	0x73, 0x69, 0x63, 0x12, 0x16, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x75,
	0x73, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x4d, 0x75, 0x73, 0x69, 0x63, 0x73, 0x12, 0x1a, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x68, 0x61, 0x6d, 0x65, 0x67, 0x61, 0x73, 0x68, 0x69, 0x2f, 0x6d, 0x75, 0x73, 0x69, 0x63,
	0x41, 0x70, 0x69, 0x57, 0x69, 0x74, 0x68, 0x47, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_music_proto_rawDescOnce sync.Once
	file_music_proto_rawDescData = file_music_proto_rawDesc
)

func file_music_proto_rawDescGZIP() []byte {
	file_music_proto_rawDescOnce.Do(func() {
		file_music_proto_rawDescData = protoimpl.X.CompressGZIP(file_music_proto_rawDescData)
	})
	return file_music_proto_rawDescData
}

var file_music_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_music_proto_goTypes = []interface{}{
	(*Music)(nil),                // 0: music.Music
	(*GetMusicRequest)(nil),      // 1: music.GetMusicRequest
	(*GetMusicResponse)(nil),     // 2: music.GetMusicResponse
	(*GetAllMusicsRequest)(nil),  // 3: music.GetAllMusicsRequest
	(*GetAllMusicsResponse)(nil), // 4: music.GetAllMusicsResponse
}
var file_music_proto_depIdxs = []int32{
	0, // 0: music.GetMusicResponse.music:type_name -> music.Music
	0, // 1: music.GetAllMusicsResponse.music:type_name -> music.Music
	1, // 2: music.MusicService.GetMusic:input_type -> music.GetMusicRequest
	3, // 3: music.MusicService.GetAllMusics:input_type -> music.GetAllMusicsRequest
	2, // 4: music.MusicService.GetMusic:output_type -> music.GetMusicResponse
	4, // 5: music.MusicService.GetAllMusics:output_type -> music.GetAllMusicsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_music_proto_init() }
func file_music_proto_init() {
	if File_music_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_music_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Music); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_music_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMusicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_music_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMusicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_music_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllMusicsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_music_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllMusicsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_music_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_music_proto_goTypes,
		DependencyIndexes: file_music_proto_depIdxs,
		MessageInfos:      file_music_proto_msgTypes,
	}.Build()
	File_music_proto = out.File
	file_music_proto_rawDesc = nil
	file_music_proto_goTypes = nil
	file_music_proto_depIdxs = nil
}
